### ISSUE TITLE
Integrate MailChimp with newsletter component

### ISSUE THREAD

**Issue by adropofilm** [CareerCatalyst/Career-Catalyst#59]
1. Look through the MailChimp docs and figure out how to make the list for our newsletter.
2. Integrate the  **Add member to mailing list** endpoint below into the newsletter component
  * POST {base_url}/lists/{list_id}/members 
3. When a success occurs we can just console.log or show an alert in the UI using JS for now. Whatever makes most sense to you. We'll create a follow up ticket that shows a snackbar.

**Additional Notes:**
We'll use MailChimp API. They use the term "member" for user, so from hereon forth that's the word I'll use as well for consistency. 

We'll create a mailing list and anytime a member submits their email address using the "newsletter"  input field successfully, we'll add them to the MailChimp mailing list. We will also use MailChimp for sending out emails, and also removing members from the mailing list when they click the "unsubscribe" link we'll also include in any emails that are sent out.

The endpoints of interest are:
- **Add member to mailing list** POST {base_url}/lists/{list_id}/members
- **Unsubscribe member from mailing list** PUT {base_url}/lists/{list_id}/members/{subscriber_hash}
   * We'll pass in the `status`: "unsubscribed" as a body parameter to unsubscribe the member from our mailing list

For sending the MailChimp emails, we can do that from the MailChimp UI.

**Comment by ghost** [comment]
Update newsletter component for forced user validation

**Comment by ghost** [comment]
Snackbar component for successful post with sending Welcome Email for verification of sign up. 

Example: https://mui.com/material-ui/react-snackbar/

**Comment by ghost** [comment]
Using the MailChimp Form builder to create our newsletter sign up process we may need to hide the form action link so people cant spam post requests
