### ISSUE TITLE
Landing page styling updates

### ISSUE THREAD

**Issue by adropofilm** [CareerCatalyst/Career-Catalyst#67]
We need to standardize a few things to ensure that styling is as expected:
1.  Standardize header font size

![Image](https://user-images.githubusercontent.com/9134674/233832558-00390df9-f6f3-4684-966d-8a7cd3cdb203.jpg)
2. Update logo in header, replace with the svg below. 

![Image](https://user-images.githubusercontent.com/9134674/233832830-7d5c97e4-b935-458d-8f64-258bac83a582.svg)
3. Center text in the GuideCard.astro

![Image](https://user-images.githubusercontent.com/9134674/233832908-d3085ac4-cab9-40ae-9f41-21e42717bc74.jpg)
4. Update newsletter button in the hero component to navigate to the "Join our Newsletter" footer at the bottom of the page when clicked on.

![Image](https://user-images.githubusercontent.com/9134674/233833131-c91ed0a8-95a2-4e10-ab1f-7861f087826f.jpg)

**Comment by jamilsinno** [comment]
#69
