### ISSUE TITLE
Complete conversion of all slots to named slots

### ISSUE THREAD

**Issue by adropofilm** [CareerCatalyst/Career-Catalyst#72]
-

**Comment by ghost** [comment]
Giving a div and slot attribute to the index.astro
fixed bringing back the site components
If the defaultLayout.astro has the name of slotMain

## Index.astro
![Image](https://user-images.githubusercontent.com/92832561/235364712-b38dc163-649b-4c95-9812-b0a89573007b.png)

## DeafultLauout.astro
![Image](https://user-images.githubusercontent.com/92832561/235364742-fc7f5812-18a2-44f4-a66d-d891bc3d9c81.png)

**Comment by ghost** [comment]
## Header.astro

This needed each li to have the slot="slotNav"


![Image](https://user-images.githubusercontent.com/92832561/235364862-ff64ac56-05d0-4898-b53e-a074e83785a6.png)

## Navigation.astro

This needed the slot component of name="slotNav"


![Image](https://user-images.githubusercontent.com/92832561/235364913-327678fa-3aec-43fd-98e7-d91381625d69.png)

**Comment by ghost** [comment]
Files needed to be fixed/looked at for any future errors would be 

src/components/ContentMedia.astro
src/components/GuidePageContainer.astro
src/components/Hero.astro
src/layouts/MarkdownLayout.astro
