### ISSUE TITLE
Adjust background for navbar in mobile

### ISSUE THREAD

**Issue by adropofilm** [CareerCatalyst/Career-Catalyst#75]
**Expected**:
- Update menu to take entire viewport height & width
- Center menu items left or right (dealer's choice, determine which is more accessible)
- Update bg color to be: #293345

![Image](https://user-images.githubusercontent.com/9134674/236347365-25731b17-cbd3-4be6-b42f-3a04a3d52d28.jpg)

**Comment by rcmtcristian** [comment]
Might consider changing it to a drop down menu in this style as i work on the prototype for mobile 
![Image](https://user-images.githubusercontent.com/20276785/236351343-7c39793a-f799-470d-aa49-e8540928d879.png)
