### ISSUE TITLE
Remove padding from the top of the hero

### ISSUE THREAD

**Issue by adropofilm** [CareerCatalyst/Career-Catalyst#79]
Remove padding between hero and top of page

![Image](https://user-images.githubusercontent.com/9134674/236350541-5c82ff03-5319-4d4a-ac9f-273297a5f60e.jpg)

**Comment by rcmtcristian** [comment]
in the navigation component change this to a py-2
![Image](https://user-images.githubusercontent.com/20276785/236354879-12fb538a-78bc-4ccd-addf-6bca38a99838.png)

**Comment by jamilsinno** [comment]
pr #81
