### ISSUE TITLE
Spike - Determine open-source (or free) email integration to use for listserv

### ISSUE THREAD

**Issue by adropofilm** [CareerCatalyst/Career-Catalyst#8]

**Comment by adropofilm** [comment]
We'll use MailChimp API. They use the term "member" for user, so from hereon forth that's the word I'll use as well for consistency. 

We'll create a mailing list and anytime a member submits their email address using the "newsletter"  input field successfully, we'll add them to the MailChimp mailing list. We will also use MailChimp for sending out emails, and also removing members from the mailing list when they click the "unsubscribe" link we'll also include in any emails that are sent out.

The endpoints of interest are:
- **Add member to mailing list** POST {base_url}/lists/{list_id}/members
- **Unsubscribe member from mailing list** PUT {base_url}/lists/{list_id}/members/{subscriber_hash}
   * We'll pass in the `status`: "unsubscribed" as a body parameter to unsubscribe the member from our mailing list

For sending the MailChimp emails, we can do that from the MailChimp UI.

**Comment by ghost** [comment]
https://mailchimp.com/developer/marketing/api/list-members/
